// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Cat3
type Cat3 struct {
	Meow OptInt32 `json:"meow"`
}

// GetMeow returns the value of Meow.
func (s *Cat3) GetMeow() OptInt32 {
	return s.Meow
}

// SetMeow sets the value of Meow.
func (s *Cat3) SetMeow(val OptInt32) {
	s.Meow = val
}

// Ref: #/components/schemas/Cat5
type Cat5 struct {
	Kind Cat5Kind `json:"kind"`
	Meow OptInt32 `json:"meow"`
}

// GetKind returns the value of Kind.
func (s *Cat5) GetKind() Cat5Kind {
	return s.Kind
}

// GetMeow returns the value of Meow.
func (s *Cat5) GetMeow() OptInt32 {
	return s.Meow
}

// SetKind sets the value of Kind.
func (s *Cat5) SetKind(val Cat5Kind) {
	s.Kind = val
}

// SetMeow sets the value of Meow.
func (s *Cat5) SetMeow(val OptInt32) {
	s.Meow = val
}

type Cat5Kind string

const (
	Cat5KindCat Cat5Kind = "cat"
)

// AllValues returns all Cat5Kind values.
func (Cat5Kind) AllValues() []Cat5Kind {
	return []Cat5Kind{
		Cat5KindCat,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Cat5Kind) MarshalText() ([]byte, error) {
	switch s {
	case Cat5KindCat:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Cat5Kind) UnmarshalText(data []byte) error {
	switch Cat5Kind(data) {
	case Cat5KindCat:
		*s = Cat5KindCat
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Cat6
type Cat6 struct {
	Name string `json:"name"`
	Meow bool   `json:"meow"`
}

// GetName returns the value of Name.
func (s *Cat6) GetName() string {
	return s.Name
}

// GetMeow returns the value of Meow.
func (s *Cat6) GetMeow() bool {
	return s.Meow
}

// SetName sets the value of Name.
func (s *Cat6) SetName(val string) {
	s.Name = val
}

// SetMeow sets the value of Meow.
func (s *Cat6) SetMeow(val bool) {
	s.Meow = val
}

// Ref: #/components/schemas/Cat7
type Cat7 struct {
	ID   Cat7ID `json:"id"`
	Name string `json:"name"`
	Meow bool   `json:"meow"`
}

// GetID returns the value of ID.
func (s *Cat7) GetID() Cat7ID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Cat7) GetName() string {
	return s.Name
}

// GetMeow returns the value of Meow.
func (s *Cat7) GetMeow() bool {
	return s.Meow
}

// SetID sets the value of ID.
func (s *Cat7) SetID(val Cat7ID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Cat7) SetName(val string) {
	s.Name = val
}

// SetMeow sets the value of Meow.
func (s *Cat7) SetMeow(val bool) {
	s.Meow = val
}

type Cat7ID string

const (
	Cat7IDCatCatCat Cat7ID = "cat-cat-cat"
)

// AllValues returns all Cat7ID values.
func (Cat7ID) AllValues() []Cat7ID {
	return []Cat7ID{
		Cat7IDCatCatCat,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Cat7ID) MarshalText() ([]byte, error) {
	switch s {
	case Cat7IDCatCatCat:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Cat7ID) UnmarshalText(data []byte) error {
	switch Cat7ID(data) {
	case Cat7IDCatCatCat:
		*s = Cat7IDCatCatCat
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Cat8
type Cat8 struct {
	Meow OptInt32 `json:"meow"`
}

// GetMeow returns the value of Meow.
func (s *Cat8) GetMeow() OptInt32 {
	return s.Meow
}

// SetMeow sets the value of Meow.
func (s *Cat8) SetMeow(val OptInt32) {
	s.Meow = val
}

type CreateReq struct {
	Body ThePet `json:"body"`
}

// GetBody returns the value of Body.
func (s *CreateReq) GetBody() ThePet {
	return s.Body
}

// SetBody sets the value of Body.
func (s *CreateReq) SetBody(val ThePet) {
	s.Body = val
}

// Ref: #/components/schemas/Dog3
type Dog3 struct {
	Bark OptString `json:"bark"`
}

// GetBark returns the value of Bark.
func (s *Dog3) GetBark() OptString {
	return s.Bark
}

// SetBark sets the value of Bark.
func (s *Dog3) SetBark(val OptString) {
	s.Bark = val
}

// Ref: #/components/schemas/Dog5
type Dog5 struct {
	Kind Dog5Kind  `json:"kind"`
	Bark OptString `json:"bark"`
}

// GetKind returns the value of Kind.
func (s *Dog5) GetKind() Dog5Kind {
	return s.Kind
}

// GetBark returns the value of Bark.
func (s *Dog5) GetBark() OptString {
	return s.Bark
}

// SetKind sets the value of Kind.
func (s *Dog5) SetKind(val Dog5Kind) {
	s.Kind = val
}

// SetBark sets the value of Bark.
func (s *Dog5) SetBark(val OptString) {
	s.Bark = val
}

type Dog5Kind string

const (
	Dog5KindDog Dog5Kind = "dog"
)

// AllValues returns all Dog5Kind values.
func (Dog5Kind) AllValues() []Dog5Kind {
	return []Dog5Kind{
		Dog5KindDog,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Dog5Kind) MarshalText() ([]byte, error) {
	switch s {
	case Dog5KindDog:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Dog5Kind) UnmarshalText(data []byte) error {
	switch Dog5Kind(data) {
	case Dog5KindDog:
		*s = Dog5KindDog
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Dog6
type Dog6 struct {
	Name string `json:"name"`
	Bark bool   `json:"bark"`
}

// GetName returns the value of Name.
func (s *Dog6) GetName() string {
	return s.Name
}

// GetBark returns the value of Bark.
func (s *Dog6) GetBark() bool {
	return s.Bark
}

// SetName sets the value of Name.
func (s *Dog6) SetName(val string) {
	s.Name = val
}

// SetBark sets the value of Bark.
func (s *Dog6) SetBark(val bool) {
	s.Bark = val
}

// Ref: #/components/schemas/Dog7
type Dog7 struct {
	ID   Dog7ID `json:"id"`
	Name string `json:"name"`
	Bark bool   `json:"bark"`
}

// GetID returns the value of ID.
func (s *Dog7) GetID() Dog7ID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Dog7) GetName() string {
	return s.Name
}

// GetBark returns the value of Bark.
func (s *Dog7) GetBark() bool {
	return s.Bark
}

// SetID sets the value of ID.
func (s *Dog7) SetID(val Dog7ID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Dog7) SetName(val string) {
	s.Name = val
}

// SetBark sets the value of Bark.
func (s *Dog7) SetBark(val bool) {
	s.Bark = val
}

type Dog7ID string

const (
	Dog7IDDogDogDog Dog7ID = "dog-dog-dog"
)

// AllValues returns all Dog7ID values.
func (Dog7ID) AllValues() []Dog7ID {
	return []Dog7ID{
		Dog7IDDogDogDog,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Dog7ID) MarshalText() ([]byte, error) {
	switch s {
	case Dog7IDDogDogDog:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Dog7ID) UnmarshalText(data []byte) error {
	switch Dog7ID(data) {
	case Dog7IDDogDogDog:
		*s = Dog7IDDogDogDog
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Dog8
type Dog8 struct {
	Bark OptString `json:"bark"`
}

// GetBark returns the value of Bark.
func (s *Dog8) GetBark() OptString {
	return s.Bark
}

// SetBark sets the value of Bark.
func (s *Dog8) SetBark(val OptString) {
	s.Bark = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

func (*ErrorStatusCode) readRes() {}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Pet
type Pet struct {
	Name   string     `json:"name"`
	Weight OptFloat32 `json:"weight"`
	// Discriminator property for Pet.
	Kind string `json:"kind"`
}

// GetName returns the value of Name.
func (s *Pet) GetName() string {
	return s.Name
}

// GetWeight returns the value of Weight.
func (s *Pet) GetWeight() OptFloat32 {
	return s.Weight
}

// GetKind returns the value of Kind.
func (s *Pet) GetKind() string {
	return s.Kind
}

// SetName sets the value of Name.
func (s *Pet) SetName(val string) {
	s.Name = val
}

// SetWeight sets the value of Weight.
func (s *Pet) SetWeight(val OptFloat32) {
	s.Weight = val
}

// SetKind sets the value of Kind.
func (s *Pet) SetKind(val string) {
	s.Kind = val
}

// Ref: #/components/schemas/Pet2
type Pet2 struct {
	Name   string     `json:"name"`
	Weight OptFloat32 `json:"weight"`
	// Discriminator property for Pet2.
	ID string `json:"id"`
}

// GetName returns the value of Name.
func (s *Pet2) GetName() string {
	return s.Name
}

// GetWeight returns the value of Weight.
func (s *Pet2) GetWeight() OptFloat32 {
	return s.Weight
}

// GetID returns the value of ID.
func (s *Pet2) GetID() string {
	return s.ID
}

// SetName sets the value of Name.
func (s *Pet2) SetName(val string) {
	s.Name = val
}

// SetWeight sets the value of Weight.
func (s *Pet2) SetWeight(val OptFloat32) {
	s.Weight = val
}

// SetID sets the value of ID.
func (s *Pet2) SetID(val string) {
	s.ID = val
}

// Ref: #/components/schemas/Pet4
// Pet4 represents sum type.
type Pet4 struct {
	Type Pet4Type // switch on this field
	Cat3 Cat3
	Dog3 Dog3
}

// Pet4Type is oneOf type of Pet4.
type Pet4Type string

// Possible values for Pet4Type.
const (
	Cat3Pet4 Pet4Type = "Cat3"
	Dog3Pet4 Pet4Type = "Dog3"
)

// IsCat3 reports whether Pet4 is Cat3.
func (s Pet4) IsCat3() bool { return s.Type == Cat3Pet4 }

// IsDog3 reports whether Pet4 is Dog3.
func (s Pet4) IsDog3() bool { return s.Type == Dog3Pet4 }

// SetCat3 sets Pet4 to Cat3.
func (s *Pet4) SetCat3(v Cat3) {
	s.Type = Cat3Pet4
	s.Cat3 = v
}

// GetCat3 returns Cat3 and true boolean if Pet4 is Cat3.
func (s Pet4) GetCat3() (v Cat3, ok bool) {
	if !s.IsCat3() {
		return v, false
	}
	return s.Cat3, true
}

// NewCat3Pet4 returns new Pet4 from Cat3.
func NewCat3Pet4(v Cat3) Pet4 {
	var s Pet4
	s.SetCat3(v)
	return s
}

// SetDog3 sets Pet4 to Dog3.
func (s *Pet4) SetDog3(v Dog3) {
	s.Type = Dog3Pet4
	s.Dog3 = v
}

// GetDog3 returns Dog3 and true boolean if Pet4 is Dog3.
func (s Pet4) GetDog3() (v Dog3, ok bool) {
	if !s.IsDog3() {
		return v, false
	}
	return s.Dog3, true
}

// NewDog3Pet4 returns new Pet4 from Dog3.
func NewDog3Pet4(v Dog3) Pet4 {
	var s Pet4
	s.SetDog3(v)
	return s
}

// Ref: #/components/schemas/Pet5
type Pet5 struct {
	OneOf Pet5Sum
}

// GetOneOf returns the value of OneOf.
func (s *Pet5) GetOneOf() Pet5Sum {
	return s.OneOf
}

// SetOneOf sets the value of OneOf.
func (s *Pet5) SetOneOf(val Pet5Sum) {
	s.OneOf = val
}

// Pet5Sum represents sum type.
type Pet5Sum struct {
	Type Pet5SumType // switch on this field
	Cat5 Cat5
	Dog5 Dog5
}

// Pet5SumType is oneOf type of Pet5Sum.
type Pet5SumType string

// Possible values for Pet5SumType.
const (
	Cat5Pet5Sum Pet5SumType = "cat"
	Dog5Pet5Sum Pet5SumType = "dog"
)

// IsCat5 reports whether Pet5Sum is Cat5.
func (s Pet5Sum) IsCat5() bool { return s.Type == Cat5Pet5Sum }

// IsDog5 reports whether Pet5Sum is Dog5.
func (s Pet5Sum) IsDog5() bool { return s.Type == Dog5Pet5Sum }

// SetCat5 sets Pet5Sum to Cat5.
func (s *Pet5Sum) SetCat5(v Cat5) {
	s.Type = Cat5Pet5Sum
	s.Cat5 = v
}

// GetCat5 returns Cat5 and true boolean if Pet5Sum is Cat5.
func (s Pet5Sum) GetCat5() (v Cat5, ok bool) {
	if !s.IsCat5() {
		return v, false
	}
	return s.Cat5, true
}

// NewCat5Pet5Sum returns new Pet5Sum from Cat5.
func NewCat5Pet5Sum(v Cat5) Pet5Sum {
	var s Pet5Sum
	s.SetCat5(v)
	return s
}

// SetDog5 sets Pet5Sum to Dog5.
func (s *Pet5Sum) SetDog5(v Dog5) {
	s.Type = Dog5Pet5Sum
	s.Dog5 = v
}

// GetDog5 returns Dog5 and true boolean if Pet5Sum is Dog5.
func (s Pet5Sum) GetDog5() (v Dog5, ok bool) {
	if !s.IsDog5() {
		return v, false
	}
	return s.Dog5, true
}

// NewDog5Pet5Sum returns new Pet5Sum from Dog5.
func NewDog5Pet5Sum(v Dog5) Pet5Sum {
	var s Pet5Sum
	s.SetDog5(v)
	return s
}

// Ref: #/components/schemas/Pet6
type Pet6 struct {
	OneOf Pet6Sum
}

// GetOneOf returns the value of OneOf.
func (s *Pet6) GetOneOf() Pet6Sum {
	return s.OneOf
}

// SetOneOf sets the value of OneOf.
func (s *Pet6) SetOneOf(val Pet6Sum) {
	s.OneOf = val
}

// Ref: #/components/schemas/Pet6Cat
type Pet6Cat struct {
	DataKind Pet6CatDataKind `json:"dataKind"`
	Data     Cat6            `json:"data"`
}

// GetDataKind returns the value of DataKind.
func (s *Pet6Cat) GetDataKind() Pet6CatDataKind {
	return s.DataKind
}

// GetData returns the value of Data.
func (s *Pet6Cat) GetData() Cat6 {
	return s.Data
}

// SetDataKind sets the value of DataKind.
func (s *Pet6Cat) SetDataKind(val Pet6CatDataKind) {
	s.DataKind = val
}

// SetData sets the value of Data.
func (s *Pet6Cat) SetData(val Cat6) {
	s.Data = val
}

type Pet6CatDataKind string

const (
	Pet6CatDataKindCat Pet6CatDataKind = "cat"
)

// AllValues returns all Pet6CatDataKind values.
func (Pet6CatDataKind) AllValues() []Pet6CatDataKind {
	return []Pet6CatDataKind{
		Pet6CatDataKindCat,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Pet6CatDataKind) MarshalText() ([]byte, error) {
	switch s {
	case Pet6CatDataKindCat:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Pet6CatDataKind) UnmarshalText(data []byte) error {
	switch Pet6CatDataKind(data) {
	case Pet6CatDataKindCat:
		*s = Pet6CatDataKindCat
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Pet6Dog
type Pet6Dog struct {
	DataKind Pet6DogDataKind `json:"dataKind"`
	Data     Dog6            `json:"data"`
}

// GetDataKind returns the value of DataKind.
func (s *Pet6Dog) GetDataKind() Pet6DogDataKind {
	return s.DataKind
}

// GetData returns the value of Data.
func (s *Pet6Dog) GetData() Dog6 {
	return s.Data
}

// SetDataKind sets the value of DataKind.
func (s *Pet6Dog) SetDataKind(val Pet6DogDataKind) {
	s.DataKind = val
}

// SetData sets the value of Data.
func (s *Pet6Dog) SetData(val Dog6) {
	s.Data = val
}

type Pet6DogDataKind string

const (
	Pet6DogDataKindDog Pet6DogDataKind = "dog"
)

// AllValues returns all Pet6DogDataKind values.
func (Pet6DogDataKind) AllValues() []Pet6DogDataKind {
	return []Pet6DogDataKind{
		Pet6DogDataKindDog,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Pet6DogDataKind) MarshalText() ([]byte, error) {
	switch s {
	case Pet6DogDataKindDog:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Pet6DogDataKind) UnmarshalText(data []byte) error {
	switch Pet6DogDataKind(data) {
	case Pet6DogDataKindDog:
		*s = Pet6DogDataKindDog
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Pet6Sum represents sum type.
type Pet6Sum struct {
	Type    Pet6SumType // switch on this field
	Pet6Cat Pet6Cat
	Pet6Dog Pet6Dog
}

// Pet6SumType is oneOf type of Pet6Sum.
type Pet6SumType string

// Possible values for Pet6SumType.
const (
	Pet6CatPet6Sum Pet6SumType = "cat"
	Pet6DogPet6Sum Pet6SumType = "dog"
)

// IsPet6Cat reports whether Pet6Sum is Pet6Cat.
func (s Pet6Sum) IsPet6Cat() bool { return s.Type == Pet6CatPet6Sum }

// IsPet6Dog reports whether Pet6Sum is Pet6Dog.
func (s Pet6Sum) IsPet6Dog() bool { return s.Type == Pet6DogPet6Sum }

// SetPet6Cat sets Pet6Sum to Pet6Cat.
func (s *Pet6Sum) SetPet6Cat(v Pet6Cat) {
	s.Type = Pet6CatPet6Sum
	s.Pet6Cat = v
}

// GetPet6Cat returns Pet6Cat and true boolean if Pet6Sum is Pet6Cat.
func (s Pet6Sum) GetPet6Cat() (v Pet6Cat, ok bool) {
	if !s.IsPet6Cat() {
		return v, false
	}
	return s.Pet6Cat, true
}

// NewPet6CatPet6Sum returns new Pet6Sum from Pet6Cat.
func NewPet6CatPet6Sum(v Pet6Cat) Pet6Sum {
	var s Pet6Sum
	s.SetPet6Cat(v)
	return s
}

// SetPet6Dog sets Pet6Sum to Pet6Dog.
func (s *Pet6Sum) SetPet6Dog(v Pet6Dog) {
	s.Type = Pet6DogPet6Sum
	s.Pet6Dog = v
}

// GetPet6Dog returns Pet6Dog and true boolean if Pet6Sum is Pet6Dog.
func (s Pet6Sum) GetPet6Dog() (v Pet6Dog, ok bool) {
	if !s.IsPet6Dog() {
		return v, false
	}
	return s.Pet6Dog, true
}

// NewPet6DogPet6Sum returns new Pet6Sum from Pet6Dog.
func NewPet6DogPet6Sum(v Pet6Dog) Pet6Sum {
	var s Pet6Sum
	s.SetPet6Dog(v)
	return s
}

// Ref: #/components/schemas/Pet7
type Pet7 struct {
	OneOf Pet7Sum
}

// GetOneOf returns the value of OneOf.
func (s *Pet7) GetOneOf() Pet7Sum {
	return s.OneOf
}

// SetOneOf sets the value of OneOf.
func (s *Pet7) SetOneOf(val Pet7Sum) {
	s.OneOf = val
}

// Pet7Sum represents sum type.
type Pet7Sum struct {
	Type Pet7SumType // switch on this field
	Cat7 Cat7
	Dog7 Dog7
}

// Pet7SumType is oneOf type of Pet7Sum.
type Pet7SumType string

// Possible values for Pet7SumType.
const (
	Cat7Pet7Sum Pet7SumType = "cat-cat-cat"
	Dog7Pet7Sum Pet7SumType = "dog-dog-dog"
)

// IsCat7 reports whether Pet7Sum is Cat7.
func (s Pet7Sum) IsCat7() bool { return s.Type == Cat7Pet7Sum }

// IsDog7 reports whether Pet7Sum is Dog7.
func (s Pet7Sum) IsDog7() bool { return s.Type == Dog7Pet7Sum }

// SetCat7 sets Pet7Sum to Cat7.
func (s *Pet7Sum) SetCat7(v Cat7) {
	s.Type = Cat7Pet7Sum
	s.Cat7 = v
}

// GetCat7 returns Cat7 and true boolean if Pet7Sum is Cat7.
func (s Pet7Sum) GetCat7() (v Cat7, ok bool) {
	if !s.IsCat7() {
		return v, false
	}
	return s.Cat7, true
}

// NewCat7Pet7Sum returns new Pet7Sum from Cat7.
func NewCat7Pet7Sum(v Cat7) Pet7Sum {
	var s Pet7Sum
	s.SetCat7(v)
	return s
}

// SetDog7 sets Pet7Sum to Dog7.
func (s *Pet7Sum) SetDog7(v Dog7) {
	s.Type = Dog7Pet7Sum
	s.Dog7 = v
}

// GetDog7 returns Dog7 and true boolean if Pet7Sum is Dog7.
func (s Pet7Sum) GetDog7() (v Dog7, ok bool) {
	if !s.IsDog7() {
		return v, false
	}
	return s.Dog7, true
}

// NewDog7Pet7Sum returns new Pet7Sum from Dog7.
func NewDog7Pet7Sum(v Dog7) Pet7Sum {
	var s Pet7Sum
	s.SetDog7(v)
	return s
}

// Ref: #/components/schemas/Pet8
type Pet8 struct {
	OneOf Pet8Sum
}

// GetOneOf returns the value of OneOf.
func (s *Pet8) GetOneOf() Pet8Sum {
	return s.OneOf
}

// SetOneOf sets the value of OneOf.
func (s *Pet8) SetOneOf(val Pet8Sum) {
	s.OneOf = val
}

// Pet8Sum represents sum type.
type Pet8Sum struct {
	Type Pet8SumType // switch on this field
	Cat8 Cat8
	Dog8 Dog8
}

// Pet8SumType is oneOf type of Pet8Sum.
type Pet8SumType string

// Possible values for Pet8SumType.
const (
	Cat8Pet8Sum Pet8SumType = "cat"
	Dog8Pet8Sum Pet8SumType = "dog"
)

// IsCat8 reports whether Pet8Sum is Cat8.
func (s Pet8Sum) IsCat8() bool { return s.Type == Cat8Pet8Sum }

// IsDog8 reports whether Pet8Sum is Dog8.
func (s Pet8Sum) IsDog8() bool { return s.Type == Dog8Pet8Sum }

// SetCat8 sets Pet8Sum to Cat8.
func (s *Pet8Sum) SetCat8(v Cat8) {
	s.Type = Cat8Pet8Sum
	s.Cat8 = v
}

// GetCat8 returns Cat8 and true boolean if Pet8Sum is Cat8.
func (s Pet8Sum) GetCat8() (v Cat8, ok bool) {
	if !s.IsCat8() {
		return v, false
	}
	return s.Cat8, true
}

// NewCat8Pet8Sum returns new Pet8Sum from Cat8.
func NewCat8Pet8Sum(v Cat8) Pet8Sum {
	var s Pet8Sum
	s.SetCat8(v)
	return s
}

// SetDog8 sets Pet8Sum to Dog8.
func (s *Pet8Sum) SetDog8(v Dog8) {
	s.Type = Dog8Pet8Sum
	s.Dog8 = v
}

// GetDog8 returns Dog8 and true boolean if Pet8Sum is Dog8.
func (s Pet8Sum) GetDog8() (v Dog8, ok bool) {
	if !s.IsDog8() {
		return v, false
	}
	return s.Dog8, true
}

// NewDog8Pet8Sum returns new Pet8Sum from Dog8.
func NewDog8Pet8Sum(v Dog8) Pet8Sum {
	var s Pet8Sum
	s.SetDog8(v)
	return s
}

// Ref: #/components/schemas/ThePet
type ThePet struct {
	Pet  Pet  `json:"pet"`
	Pet2 Pet2 `json:"pet2"`
	Pet4 Pet4 `json:"pet4"`
	Pet5 Pet5 `json:"pet5"`
	Pet6 Pet6 `json:"pet6"`
	Pet7 Pet7 `json:"pet7"`
	Pet8 Pet8 `json:"pet8"`
}

// GetPet returns the value of Pet.
func (s *ThePet) GetPet() Pet {
	return s.Pet
}

// GetPet2 returns the value of Pet2.
func (s *ThePet) GetPet2() Pet2 {
	return s.Pet2
}

// GetPet4 returns the value of Pet4.
func (s *ThePet) GetPet4() Pet4 {
	return s.Pet4
}

// GetPet5 returns the value of Pet5.
func (s *ThePet) GetPet5() Pet5 {
	return s.Pet5
}

// GetPet6 returns the value of Pet6.
func (s *ThePet) GetPet6() Pet6 {
	return s.Pet6
}

// GetPet7 returns the value of Pet7.
func (s *ThePet) GetPet7() Pet7 {
	return s.Pet7
}

// GetPet8 returns the value of Pet8.
func (s *ThePet) GetPet8() Pet8 {
	return s.Pet8
}

// SetPet sets the value of Pet.
func (s *ThePet) SetPet(val Pet) {
	s.Pet = val
}

// SetPet2 sets the value of Pet2.
func (s *ThePet) SetPet2(val Pet2) {
	s.Pet2 = val
}

// SetPet4 sets the value of Pet4.
func (s *ThePet) SetPet4(val Pet4) {
	s.Pet4 = val
}

// SetPet5 sets the value of Pet5.
func (s *ThePet) SetPet5(val Pet5) {
	s.Pet5 = val
}

// SetPet6 sets the value of Pet6.
func (s *ThePet) SetPet6(val Pet6) {
	s.Pet6 = val
}

// SetPet7 sets the value of Pet7.
func (s *ThePet) SetPet7(val Pet7) {
	s.Pet7 = val
}

// SetPet8 sets the value of Pet8.
func (s *ThePet) SetPet8(val Pet8) {
	s.Pet8 = val
}

func (*ThePet) readRes() {}
