// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateOperation OperationName = "Create"
	ListOperation   OperationName = "List"
	ReadOperation   OperationName = "Read"
)
