// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Create implements create operation.
	//
	// POST /{id}
	Create(ctx context.Context, req *CreateReq, params CreateParams) (*ThePet, error)
	// List implements list operation.
	//
	// GET /
	List(ctx context.Context, params ListParams) ([]ThePet, error)
	// Read implements read operation.
	//
	// GET /{id}
	Read(ctx context.Context, params ReadParams) (ReadRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
