// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Create implements create operation.
//
// POST /{id}
func (UnimplementedHandler) Create(ctx context.Context, req *CreateReq, params CreateParams) (r *ThePet, _ error) {
	return r, ht.ErrNotImplemented
}

// Read implements read operation.
//
// GET /{id}
func (UnimplementedHandler) Read(ctx context.Context, params ReadParams) (r ReadRes, _ error) {
	return r, ht.ErrNotImplemented
}
