// Code generated by ogen, DO NOT EDIT.

package api

// SetFake set fake values.
func (s *Cat3) SetFake() {
	{
		{
			s.Meow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Cat5) SetFake() {
	{
		{
			s.Kind.SetFake()
		}
	}
	{
		{
			s.Meow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Cat5Kind) SetFake() {
	*s = Cat5KindCat
}

// SetFake set fake values.
func (s *Cat6) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Meow = true
		}
	}
}

// SetFake set fake values.
func (s *Cat7) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Meow = true
		}
	}
}

// SetFake set fake values.
func (s *Cat7ID) SetFake() {
	*s = Cat7IDCatCatCat
}

// SetFake set fake values.
func (s *Cat8) SetFake() {
	{
		{
			s.Meow.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateReq) SetFake() {
	{
		{
			s.Body.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Dog3) SetFake() {
	{
		{
			s.Bark.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Dog5) SetFake() {
	{
		{
			s.Kind.SetFake()
		}
	}
	{
		{
			s.Bark.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Dog5Kind) SetFake() {
	*s = Dog5KindDog
}

// SetFake set fake values.
func (s *Dog6) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Bark = true
		}
	}
}

// SetFake set fake values.
func (s *Dog7) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Bark = true
		}
	}
}

// SetFake set fake values.
func (s *Dog7ID) SetFake() {
	*s = Dog7IDDogDogDog
}

// SetFake set fake values.
func (s *Dog8) SetFake() {
	{
		{
			s.Bark.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.Code = int32(0)
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *OptFloat32) SetFake() {
	var elem float32
	{
		elem = float32(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt32) SetFake() {
	var elem int32
	{
		elem = int32(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *Pet) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Weight.SetFake()
		}
	}
	{
		{
			s.Kind = "string"
		}
	}
}

// SetFake set fake values.
func (s *Pet2) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Weight.SetFake()
		}
	}
	{
		{
			s.ID = "string"
		}
	}
}

// SetFake set fake values.
func (s *Pet4) SetFake() {
	var variant Cat3

	{
		variant.SetFake()
	}
	s.SetCat3(variant)
}

// SetFake set fake values.
func (s *Pet5) SetFake() {
	{
		{
			s.OneOf.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Pet5Sum) SetFake() {
	var variant Cat5

	{
		variant.SetFake()
	}
	s.SetCat5(variant)
}

// SetFake set fake values.
func (s *Pet6) SetFake() {
	{
		{
			s.OneOf.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Pet6Cat) SetFake() {
	{
		{
			s.DataKind.SetFake()
		}
	}
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Pet6CatDataKind) SetFake() {
	*s = Pet6CatDataKindCat
}

// SetFake set fake values.
func (s *Pet6Dog) SetFake() {
	{
		{
			s.DataKind.SetFake()
		}
	}
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Pet6DogDataKind) SetFake() {
	*s = Pet6DogDataKindDog
}

// SetFake set fake values.
func (s *Pet6Sum) SetFake() {
	var variant Pet6Cat

	{
		variant.SetFake()
	}
	s.SetPet6Cat(variant)
}

// SetFake set fake values.
func (s *Pet7) SetFake() {
	{
		{
			s.OneOf.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Pet7Sum) SetFake() {
	var variant Cat7

	{
		variant.SetFake()
	}
	s.SetCat7(variant)
}

// SetFake set fake values.
func (s *Pet8) SetFake() {
	{
		{
			s.OneOf.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Pet8Sum) SetFake() {
	var variant Cat8

	{
		variant.SetFake()
	}
	s.SetCat8(variant)
}

// SetFake set fake values.
func (s *ThePet) SetFake() {
	{
		{
			s.Pet.SetFake()
		}
	}
	{
		{
			s.Pet2.SetFake()
		}
	}
	{
		{
			s.Pet4.SetFake()
		}
	}
	{
		{
			s.Pet5.SetFake()
		}
	}
	{
		{
			s.Pet6.SetFake()
		}
	}
	{
		{
			s.Pet7.SetFake()
		}
	}
	{
		{
			s.Pet8.SetFake()
		}
	}
}
